apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "search.fullname" . }}
  labels:
    {{- include "search.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "search.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "search.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "search.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          livenessProbe:
            httpGet:
              port: {{ .Values.port }}
              path: {{ .Values.livenessProbe.path }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds}}
          readinessProbe:
            httpGet:
              port: {{ .Values.port }}
              path: {{ .Values.readinessProbe.path }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.profile  }}
            - name: SERVER_PORT
              value: {{ .Values.port | quote}}

            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.spring.datasource.url }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.env.spring.datasource.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.env.spring.datasource.password }}

            - name: SWAGGER_URL
              value: {{ .Values.env.swagger.url }}
            - name: SWAGGER_TITLE
              value: {{ .Values.env.swagger.title }}
            - name: SWAGGER_DESCRIPTION
              value: {{ .Values.env.swagger.description }}
            - name: SWAGGER_VERSION
              value: {{ .Values.env.swagger.version | quote}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
