crawler:
  env:
    profile: aws
    dynamodb:
      tableName: crawlerPages
    kafka:
      brokers:
        - b-1.osearchcluster.x5zpp9.c3.kafka.us-east-1.amazonaws.com:9098
        - b-2.osearchcluster.x5zpp9.c3.kafka.us-east-1.amazonaws.com:9098
      requestTopic: crawler.request
      responseTopic: crawler.response
      pageTopic: crawler.pages
      groupId: crawler.group
    service:
      crawlerThreadsCount: 6
      processorThreadsCount: 6
      pagesToKeep: 50000
      externalUrlRegex: "((http|https)://[\\w\\d:#@%/;$()~_?\\+-=\\\\\\.&]*)"
      invalidUrlRegex: ".*\\.(js|txt|json|csv|pdf|xml|mp3|mp4|avi|mov|zip|rar|exe|jpg|jpeg|gif|png|svg)$"
    rest:
      timeout: 10000
      maxRedirects: 10
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"
    swagger:
      title: Crawler API
      description: This API allows you to work with crawler service
      version: 1.6.0

  securityContext:
    fsGroup: 65534

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::464825733390:role/crawlerRole
      
  ingress:
    host: osearch.com


indexer:
  env:
    profile: aws
    neptune:
      readEndpoint: bolt://db-neptune-1.cluster-cyah5uvjzcom.us-east-1.neptune.amazonaws.com:8182/pageindex
      writeEndpoint: bolt://db-neptune-1.cluster-ro-cyah5uvjzcom.us-east-1.neptune.amazonaws.com:8182/pageindex
    kafka:
      brokers:
        - b-1.osearchcluster.x5zpp9.c3.kafka.us-east-1.amazonaws.com:9098
        - b-2.osearchcluster.x5zpp9.c3.kafka.us-east-1.amazonaws.com:9098
      in:
        topic: crawler.pages
        groupId: indexer.group
      out:
        topic: indexer.pages
    domain:
      supportedLocales: en, en-usa, en-gb, en-ca, en-au, en-nz, en-in, en-ie, en-za, en-jm, en-bz,
        en-tt, en-sg, en-my
    swagger:
      title: Indexer API
      description: This API allows you to work with indexer service
      version: 2.3.0

  securityContext:
    fsGroup: 65534

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::464825733390:role/indexerRole

  ingress:
    host: osearch.com


ranker:
  env:
    profile: aws
    aws:
      secretName: osearch-mysql-secret
      region: us-east-1
    neptune:
      readEndpoint: bolt://db-neptune-1.cluster-cyah5uvjzcom.us-east-1.neptune.amazonaws.com:8182/pageindex
    kafka:
      brokers:
        - b-1.osearchcluster.x5zpp9.c3.kafka.us-east-1.amazonaws.com:9098
        - b-2.osearchcluster.x5zpp9.c3.kafka.us-east-1.amazonaws.com:9098
      topic: indexer.pages
      groupId: ranker.group
    rank:
      pageRankIterations: 20
      pageRankDampingFactor: 0.85
      topicRankWeight: 0.6
      pageRankWeight: 0.2
      metaRankWeight: 0.1

  securityContext:
    fsGroup: 65534

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::464825733390:role/rankerRole

  ingress:
    host: osearch.com


search:
  env:
    profile: aws
    aws:
      secretName: osearch-mysql-secret
      region: us-east-1
    swagger:
      title: Search API
      description: This API allows you to search for web pages
      version: 1.1.0
  
  securityContext:
    fsGroup: 65534

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::464825733390:role/searchRole
  
  ingress:
    host: osearch.com
