crawler:
  env:
    profile: prod
    mongo:
      host: host.docker.internal
      port: 27017
      database: crawler-db
    kafka:
      brokers:
        - host.docker.internal:9092
      requestTopic: crawler.request
      responseTopic: crawler.response
      pageTopic: crawler.pages
      groupId: crawler.group
    service:
      crawlerThreadsCount: 6
      processorThreadsCount: 6
      pagesToKeep: 50000
      externalUrlRegex: "((http|https)://[\\w\\d:#@%/;$()~_?\\+-=\\\\\\.&]*)"
      invalidUrlRegex: ".*\\.(js|txt|json|csv|pdf|xml|mp3|mp4|avi|mov|zip|rar|exe|jpg|jpeg|gif|png|svg)$"
    rest:
      timeout: 10000
      maxRedirects: 10
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"
    swagger:
      title: Crawler API
      description: This API allows you to work with crawler service
      version: 1.6.0

  ingress:
    host: localhost


indexer:
  env:
    profile: prod
    neo4j:
      url: bolt://host.docker.internal/pageindex
      username: neo4j
      password: localneo
    kafka:
      brokers:
        - host.docker.internal:9092
      in:
        topic: crawler.pages
        groupId: indexer.group
      out:
        topic: indexer.pages
    domain:
      supportedLocales: en, en-usa, en-gb, en-ca, en-au, en-nz, en-in, en-ie, en-za, en-jm, en-bz,
        en-tt, en-sg, en-my
    swagger:
      title: Indexer API
      description: This API allows you to work with indexer service
      version: 2.3.0

  ingress:
    host: localhost


ranker:
  env:
    profile: prod
    spring:
      datasource:
        url: jdbc:mysql://host.docker.internal/indexes?createDatabaseIfNotExist=true
        username: root
        password: localmy
    neo4j:
      url: bolt://host.docker.internal/pageindex
      username: neo4j
      password: localneo
    kafka:
      brokers:
        - host.docker.internal:9092
      topic: indexer.pages
      groupId: ranker.group
    rank:
      pageRankIterations: 20
      pageRankDampingFactor: 0.85
      topicRankWeight: 0.6
      pageRankWeight: 0.2
      metaRankWeight: 0.1


search:
  env:
    profile: prod
    spring:
      datasource:
        url: jdbc:mysql://host.docker.internal/indexes?createDatabaseIfNotExist=true
        username: root
        password: localmy
    swagger:
      title: Search API
      description: This API allows you to search for web pages
      version: 1.1.0
      
  ingress:
    host: localhost