apiVersion: v2
name: osearch
description: An umbrella chart for aggregating osearch services
type: application
version: 1.0.0
dependencies:
  - name: crawler
    version: 1.1.0
    condition: crawler.enabled
  - name: indexer
    version: 1.0.0
    condition: indexer.enabled
  - name: ranker
    version: 1.0.0
    condition: ranker.enabled
  - name: search
    version: 1.0.0
    condition: search.enabled
