# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

port: 3306

service:
  type: ClusterIP
  port: 3306

env:
  database: indexes
  password: localmy

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  tls: []

podSecurityContext: {}

securityContext: {}

volumeClaim:
  size: 5Gi
  accessModes:
    - ReadWriteOnce

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: env-mysql-volume-claim
    persistentVolumeClaim:
      claimName: env-mysql

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
