# Default values for crawler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: atolpeko/crawler
  tag: 1.6.0
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

strategy:
  type: Recreate

port: 8080
contextPath: /crawler

livenessProbe:
  path: /crawler/actuator/health/liveness
  initialDelaySeconds: 400
  periodSeconds: 10

readinessProbe:
  path: /crawler/actuator/health/readiness
  initialDelaySeconds: 25

serviceAccount:
  create: true
  name: osearch-crawler.service-account
  annotations: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  protocol: TCP

ingress:
  enabled: true
  name: osearch-crawler-ingress
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  paths:
    - path: /crawler
      service:
        name: osearch-crawler
        port: 80  

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
