spring:
  kafka:
    consumer:
      auto-offset-reset: latest
  sql:
    init:
      mode: always
logging:
  level:
    com.osearch.ranker: INFO
    org.springframework.data.neo4j.cypher: ERROR
    org.apache.kafka: ERROR
management:
  endpoint:
    health:
      probes:
        enabled: true
