spring:
  kafka:
    consumer:
      auto-offset-reset: latest
kafka:
  maxMessageSize: 10485760
logging:
  level:
    com.osearch.crawler: INFO
    org.apache.kafka: ERROR
    org.apache.kafka.clients.consumer.ConsumerConfig: OFF
management:
  endpoint:
    health:
      probes:
        enabled: true
swagger:
  url: /swagger-ui/index.html
  controllersPackage: com.osearch.crawler.adapter.in.rest