apiVersion: v1
kind: Service
metadata:
  name: {{ include "ranker.fullname" . }}
  labels:
    {{- include "ranker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "ranker.selectorLabels" . | nindent 4 }}
