server:
  port: 8080
spring:
  kafka:
    consumer:
      auto-offset-reset: latest
  bulkMessagesCount: 50
logging:
  level:
    com.osearch.crawler: INFO
    org.apache.kafka: INFO
    org.apache.kafka.clients.consumer.ConsumerConfig: OFF
management:
  endpoint:
    health:
      probes:
        enabled: true
service:
  crawlerThreadsCount: 6
  processorThreadsCount: 6
rest:
  urlsToKeep: 20000
  timeout: 10000
  maxRedirects: 5
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.1234.567 Safari/537.36
swagger:
  title: Crawler API
  description: The API allows you to start / stop this crawler service
  version: "0.0.1"
  controllersPackage: com.osearch.crawler.inout.web
