server:
  port: 5960
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: crawler-db
  kafka:
    consumer:
      auto-offset-reset: latest
kafka:
  url: localhost:9092
  urlTopic: crawler-urls
  requestTopic: crawler-request
  responseTopic: crawler-response
  groupId: crawler-group
  maxMessageSize: 10485760
logging:
  level:
    com.osearch.crawler: DEBUG
management:
  endpoint:
    health:
      probes:
        enabled: true
service:
  crawlerThreadsCount: 1
  processorThreadsCount: 1
  urlsToKeep: 2000
rest:
  timeout: 10000
  maxRedirects: 5
  userAgent: Crawler
swagger:
  title: Crawler API [DEBUG PROFILE]
  description: The API allows you to start / stop this crawler service
  version: "0.0.1"
  controllersPackage: com.osearch.crawler.inout.web
