server:
  port: 8080
spring:
  kafka:
    consumer:
      auto-offset-reset: latest
      maxMessageSize: 10485760
logging:
  level:
    com.osearch.crawler: INFO
    org.apache.kafka: INFO
    org.apache.kafka.clients.consumer.ConsumerConfig: OFF
management:
  endpoint:
    health:
      probes:
        enabled: true
service:
  crawlerThreadsCount: 6
  processorThreadsCount: 6
  externalUrlRegex: "((http|https)://[\\w\\d:#@%/;$()~_?\\+-=\\\\\\.&]*)"
  invalidUrlRegex: ".*\\.(js|txt|json|csv|pdf|xml|mp3|mp4|avi|mov|zip|rar|exe|jpg|jpeg|gif|png|svg)$"
rest:
  pagesToKeep: 20000
  timeout: 10000
  maxRedirects: 5
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.1234.567 Safari/537.36
swagger:
  url: /swagger-ui/index.html
  title: Crawler API
  description: This API allows you to start pages crawling
  version: "1.2"
  controllersPackage: com.osearch.crawler.adapter.in.rest
