server:
  port: 5960
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: crawler-db
  kafka:
    consumer:
      auto-offset-reset: latest
kafka:
  url: localhost:9092
  urlTopic: crawler-urls
  requestTopic: crawler-request
  responseTopic: crawler-response
  groupId: crawler-group
  bulkMessagesCount: 50
logging:
  level:
    com.osearch.crawler: INFO
    org.apache.kafka: INFO
    org.apache.kafka.clients.consumer.ConsumerConfig: OFF
management:
  endpoint:
    health:
      probes:
        enabled: true
service:
  crawlerThreadsCount: 6
  processorThreadsCount: 6
  urlsToKeep: 20000
rest:
  timeout: 10000
  maxRedirects: 5
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
swagger:
  title: Crawler API [LOCAL PROFILE]
  description: The API allows you to start / stop this crawler service
  version: "0.0.1"
  controllersPackage: com.osearch.crawler.inout.web
