server:
  port: 5960
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: crawler-db
  kafka:
    consumer:
      auto-offset-reset: latest
kafka:
  url: localhost:9092
  pageTopic: crawler-pages
  requestTopic: crawler-request
  responseTopic: crawler-response
  groupId: crawler-group
  maxMessageSize: 10485760
logging:
  level:
    com.osearch.crawler: DEBUG
management:
  endpoint:
    health:
      probes:
        enabled: true
service:
  crawlerThreadsCount: 1
  processorThreadsCount: 1
  pagesToKeep: 2000
  externalUrlRegex: "((http|https)://[\\w\\d:#@%/;$()~_?\\+-=\\\\\\.&]*)"
  invalidUrlRegex: ".*\\.(js|txt|json|csv|pdf|xml|mp3|mp4|avi|mov|zip|rar|exe|jpg|jpeg|gif|png|svg)$"
rest:
  timeout: 10000
  maxRedirects: 5
  userAgent: Crawler
swagger:
  url: /swagger-ui/index.html
  title: Crawler API [DEBUG PROFILE]
  description: This API allows you to work with crawler service
  version: "1.3"
  controllersPackage: com.osearch.crawler.adapter.in.rest
