apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.volumeClaim.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.volumeClaim.size }}
