apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.volumeClaim.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.volumeClaim.size }}
