# Default values for mongodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

port: 27017

service:
  type: ClusterIP
  port: 27017

ingress:
  enabled: false
  name: env-mongodb-ingress
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

volumeClaim:
  size: 5Gi
  accessModes:
    - ReadWriteOnce

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: env-mongodb-volume-claim
    persistentVolumeClaim:
      claimName: env-mongodb

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
