server:
  port: 5970
spring:
  data:
    neo4j:
      uri: bolt://localhost:7687/pageindex
      username: neo4j
      password: localneo
  kafka:
    consumer:
      auto-offset-reset: latest
kafka:
  url: localhost:9092
  urlTopic: crawler-urls
  requestTopic: index-change
  groupId: indexer-group
service:
  threadsCount: 6
  waitBeforeRequests: 3000
logging:
  level:
    com.osearch.indexer: INFO
management:
  endpoint:
    health:
      probes:
        enabled: true
