server:
  port: 5970
spring:
  kafka:
    consumer:
      auto-offset-reset: latest
neo4j:
  url: bolt://localhost:7687/pageindex
  username: neo4j
  password: localneo
kafka:
  url: localhost:9092
  in:
    topic: crawler-pages
    groupId: indexer-group
  out:
    topic: indexer-pages
service:
  waitBeforeRequests: 3000
logging:
  level:
    org.springframework.data.neo4j.cypher: ERROR
    com.osearch.indexer: INFO
management:
  endpoint:
    health:
      probes:
        enabled: true
