server:
  port: 5970
spring:
  kafka:
    consumer:
      auto-offset-reset: latest
service:
  waitBeforeRequests: 3000
logging:
  level:
    com.osearch.indexer: INFO
management:
  endpoint:
    health:
      probes:
        enabled: true
