server:
  port: 8080
spring:
  kafka:
    consumer:
      auto-offset-reset: latest
logging:
  level:
    com.osearch.indexer: INFO
management:
  endpoint:
    health:
      probes:
        enabled: true
