# Default values for neo4j.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: neo4j
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

port: 7687

service:
  type: ClusterIP
  port: 7687

env:
  auth: neo4j/localneo

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  tls: []

podSecurityContext: {}

securityContext: {}

volumeClaim:
  size: 5Gi
  accessModes:
    - ReadWriteOnce

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: env-neo4j-volume-claim
    persistentVolumeClaim:
      claimName: env-neo4j

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
